# Generated by Django 6.0 on 2026-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('right', 'Right Sidebar'), ('top', 'Top Banner'), ('middle', 'Middle'), ('bottom', 'Bottom Banner')], max_length=20),
        ),
    ]
