# Generated by Django 6.0 on 2026-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_advertisement_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('right', 'Right Sidebar'), ('top', 'Top Banner'), ('middle', 'Middle'), ('bottom', 'Bottom Banner'), ('business_bottom', 'Business Bottom Banner')], max_length=20),
        ),
    ]
