# Generated by Django 6.0 on 2026-08-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerad',
            options={'verbose_name': 'Top Banner', 'verbose_name_plural': 'Top Banners'},
        ),
        migrations.AlterModelOptions(
            name='smallslider',
            options={'verbose_name': 'Trending News', 'verbose_name_plural': 'Trending News'},
        ),
        migrations.RemoveField(
            model_name='bannerad',
            name='title',
        ),
    ]
