# Generated by Django 6.0 on 2026-08-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_bannerad_options_alter_smallslider_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerad',
            options={'verbose_name': 'Top Banner', 'verbose_name_plural': 'Top Banner'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='title',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('right', 'Right Banner'), ('middle', 'Middle Banner'), ('bottom', 'Bottom Banner')], max_length=20),
        ),
    ]
