# Generated by Django 6.0 on 2026-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_bannerad_options_remove_advertisement_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerAd',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('top', 'Top Banner'), ('right', 'Right Banner'), ('middle', 'Middle Banner'), ('bottom', 'Bottom Banner')], max_length=20),
        ),
    ]
