# Generated by Django 6.0 on 2026-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_delete_bannerad_alter_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
