# Generated by Django 6.0 on 2026-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_news_is_featured_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='News Link'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Top News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_main_news',
            field=models.BooleanField(default=False, verbose_name='Main News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Quick Updates'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_weekend_special',
            field=models.BooleanField(default=False, verbose_name='Breaking News'),
        ),
    ]
