# Generated by Django 6.0 on 2026-09-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_news_link_alter_news_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
