# Generated by Django 6.0 on 2026-09-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_news_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_local_news',
            field=models.BooleanField(default=False, verbose_name='Local News'),
        ),
    ]
