# Generated by Django 6.0 on 2026-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_news_is_local_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link'),
        ),
    ]
